version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17 # Use Java 17 environment
    commands:
      - echo Installing Maven...
      - curl -o /tmp/apache-maven-3.8.8-bin.tar.gz https://downloads.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
      - tar xzvf /tmp/apache-maven-3.8.8-bin.tar.gz -C /tmp/
      - export PATH=$PATH:/tmp/apache-maven-3.8.8/bin # Add Maven to PATH
      - mvn -v # Verify Maven installation

  pre_build:
    commands:
      - echo Running pre-build steps...
      - mvn dependency:resolve # Resolve project dependencies

  build:
    commands:
      - echo Building the Spring Boot application...
      - mvn clean package -DskipTests # Build the project and skip tests

  post_build:
    commands:
      - echo Build completed successfully!
      - ls target # List the contents of the build directory

artifacts:
  files:
    - target/wecommunity-0.0.1-SNAPSHOT.jar # Save the generated JAR file
    - scripts/*
    - appspec.yaml

cache:
  paths:
    - ~/.m2/repository/**/* # Cache Maven local repository

